# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'proj181221' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for proj181221
  pod 'R.swift'
  pod 'lottie-ios'
  pod 'UIColor_Hex_Swift'
  pod 'SwiftyDraw'
end
